FROM python:3.10-slim

WORKDIR /app

COPY frontend /app/frontend
COPY requirements.txt /app

RUN pip install --no-cache-dir -r requirements.txt

CMD ["streamlit", "run", "frontend/app.py", "--server.port=7860", "--server.address=0.0.0.0"]